name: "Run Anchore Scan Action (ACS SARIF Demo)"

on: [push]

jobs:
  CodeQL-Analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      # Override language selection by uncommenting this and choosing your languages
      # with:
      #   languages: go, javascript, csharp, python, cpp, java

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
  Anchore-Scan-Action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag redis/datadog-exporter:latest
    - name: Run the local anchore scan action itself with sarif generation enabled
      uses: anchore/scan-action@v2
      with:
        image: "redis/datadog-exporter:latest"
        debug: false
        acs-report-enable: true
        severity-cutoff: "Critical"
    - name: Upload Anchore Scan ACS Report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
