name: Anchore Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Build
      run: docker build . --file Dockerfile --tag redis/datadog-exporter:latest
    - uses: anchore/scan-action@v1
      id: scan
      with:
        image: "redis/datadog-exporter:latest"
        fail-build: true
        severity-cutoff: critical
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: AnchoreReports
        path: ./anchore-reports/
        
