name: Anchore Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Build
      run: docker build . --file Dockerfile --tag redis/datadog-exporter:latest
    - uses: anchore/scan-action@v1
      with:
        image-reference: "redis/datadog-exporter:latest"
        dockerfile-path: "./Dockerfile"
        fail-build: true
